name: Deploy to RENDER

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github code
        uses: actions/checkout@v4

      - name: Deploying
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
